version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: self_driving_mongodb_infra
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: self_driving_redis_infra
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: self_driving_backend_infra
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    container_name: self_driving_worker_infra
    depends_on:
      - mongodb
      - redis
